[CmdletBinding()]param([Parameter(Mandatory)][ValidateSet('development','production')][string]$Environment,[Parameter(Mandatory)][string]$OutputDirectory)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;$out=[IO.Path]::GetFullPath($OutputDirectory)
if($out-eq[IO.Path]::GetPathRoot($out)-or$out-eq$root){throw 'Unsafe output directory.'};if(Test-Path -LiteralPath $out){Remove-Item -LiteralPath $out -Recurse -Force};New-Item -ItemType Directory -Path $out -Force|Out-Null
$files=@('index.html','robots.txt','sitemap.xml','.htaccess','favicon.ico','favicon-16x16.png','favicon-32x32.png','apple-touch-icon.png','icon-192.png','icon-192-maskable.png','icon-512.png','icon-512-maskable.png','site.webmanifest');$folders=@('assets','css','js','hall','cistenie-klimatizacie','servis-klimatizacie','ochrana-osobnych-udajov')
foreach($name in $files){$source=Join-Path $root $name;if(Test-Path -LiteralPath $source){Copy-Item -LiteralPath $source -Destination (Join-Path $out $name)}};foreach($name in $folders){Copy-Item -LiteralPath (Join-Path $root $name) -Destination (Join-Path $out $name) -Recurse}
$pages=@(Get-ChildItem -LiteralPath $out -Recurse -Filter *.html -File)
if($Environment-eq'development'){foreach($page in $pages){$text=Get-Content -LiteralPath $page.FullName -Raw;$text=[regex]::Replace($text,'<meta\s+name=["'']robots["''][^>]*>','',[Text.RegularExpressions.RegexOptions]::IgnoreCase);$text=$text.Replace('<meta name="viewport"','<meta name="robots" content="noindex, nofollow">' + "`n  " + '<meta name="viewport"');Set-Content -LiteralPath $page.FullName -Value $text -Encoding utf8};Set-Content -LiteralPath (Join-Path $out robots.txt) -Value "User-agent: *`nDisallow: /`n" -Encoding utf8;Remove-Item -LiteralPath (Join-Path $out sitemap.xml) -Force -ErrorAction SilentlyContinue}
else{if(!(Test-Path -LiteralPath (Join-Path $out sitemap.xml))){throw 'Production sitemap.xml is required.'};if((Get-Content -Raw (Join-Path $out robots.txt))-match'(?im)^\s*Disallow:\s*/\s*$'){throw 'Production robots.txt blocks the whole site.'};$bad=@($pages|Where-Object{(Get-Content -Raw $_.FullName)-match'(?i)noindex'});if($bad.Count){throw "Production contains noindex: $($bad.FullName -join ', ')"}}
$forbidden=@(Get-ChildItem -LiteralPath $out -Recurse -Force|Where-Object{$_.Name-match'(^\.env|\.(pem|p12|pfx|jks|keystore)$|\.md$)' -or $_.FullName-match'[\\/](docs|tests|interne|node_modules)[\\/]'});if($forbidden.Count){throw "Forbidden release entries: $($forbidden.FullName -join ', ')"};Write-Host "Built $Environment payload with $($pages.Count) HTML pages: $out"
